import {
  MarkerLifecycleState,
  NodeAssignmentState,
  NodeHealthState,
  NodeLifecycleState,
  RackCapacityState,
  RackLifecycleState,
} from '@domain/entities/asset-context.entities';
import { MarkerTargetType } from '@domain/constants/marker-target-type.enum';

export const assetContextSeedFixture = {
  racks: [
    {
      rackCode: 'RACK-HCM-A1',
      displayName: 'HCM Rack A1',
      lifecycleState: RackLifecycleState.ACTIVE,
      capacityState: RackCapacityState.AVAILABLE,
      siteCode: 'HCM-DC',
      roomCode: 'ROOM-A',
      zoneCode: 'ZONE-1',
      rowCode: 'ROW-A',
      positionCode: 'A1',
      capacityLimit: 20,
      vendor: 'Vertiv',
      metadata: { seeded: true, scenario: 'golden-path' },
    },
    {
      rackCode: 'RACK-HCM-B1',
      displayName: 'HCM Rack B1',
      lifecycleState: RackLifecycleState.READY,
      capacityState: RackCapacityState.EXPANDING,
      siteCode: 'HCM-DC',
      roomCode: 'ROOM-B',
      zoneCode: 'ZONE-2',
      rowCode: 'ROW-B',
      positionCode: 'B1',
      capacityLimit: 24,
      metadata: { seeded: true },
    },
    {
      rackCode: 'RACK-HCM-C1',
      displayName: 'HCM Rack C1',
      lifecycleState: RackLifecycleState.CREATED,
      capacityState: RackCapacityState.AVAILABLE,
      siteCode: 'HCM-DC',
      roomCode: 'ROOM-C',
      zoneCode: 'ZONE-3',
      rowCode: 'ROW-C',
      positionCode: 'C1',
      capacityLimit: 16,
      metadata: { seeded: true },
    },
    {
      rackCode: 'RACK-HCM-D1',
      displayName: 'HCM Rack D1',
      lifecycleState: RackLifecycleState.DRAINING,
      capacityState: RackCapacityState.FULL,
      siteCode: 'HCM-DC',
      roomCode: 'ROOM-D',
      zoneCode: 'ZONE-4',
      rowCode: 'ROW-D',
      positionCode: 'D1',
      capacityLimit: 18,
      metadata: { seeded: true },
    },
  ],
  nodes: [
    {
      nodeCode: 'NODE-HCM-A1-01',
      displayName: 'Compute A1-01',
      hostname: 'compute-a1-01.dc.local',
      nodeType: 'compute',
      source: 'collector',
      lifecycleState: NodeLifecycleState.ACTIVE,
      assignmentState: NodeAssignmentState.ASSIGNED,
      rackCode: 'RACK-HCM-A1',
      managementIp: '10.10.1.11',
      metadata: { seeded: true, scenario: 'golden-path' },
    },
    {
      nodeCode: 'NODE-HCM-B1-01',
      displayName: 'Compute B1-01',
      hostname: 'compute-b1-01.dc.local',
      nodeType: 'compute',
      source: 'collector',
      lifecycleState: NodeLifecycleState.READY,
      assignmentState: NodeAssignmentState.UNASSIGNED,
      managementIp: '10.10.2.11',
      metadata: { seeded: true },
    },
    {
      nodeCode: 'NODE-HCM-D1-01',
      displayName: 'Storage D1-01',
      hostname: 'storage-d1-01.dc.local',
      nodeType: 'storage',
      source: 'collector',
      lifecycleState: NodeLifecycleState.DRAINING,
      assignmentState: NodeAssignmentState.ASSIGNED,
      rackCode: 'RACK-HCM-D1',
      managementIp: '10.10.4.11',
      metadata: { seeded: true },
    },
    {
      nodeCode: 'NODE-HCM-DISC-01',
      displayName: 'Discovered Node 01',
      hostname: 'discover-01.dc.local',
      nodeType: 'compute',
      source: 'collector',
      lifecycleState: NodeLifecycleState.DISCOVERED,
      assignmentState: NodeAssignmentState.UNASSIGNED,
      managementIp: '10.10.9.11',
      metadata: { seeded: true },
    },
  ],
  markers: [
    {
      markerCode: 'MK-RACK-A1',
      displayLabel: 'Rack A1 Marker',
      lifecycleState: MarkerLifecycleState.ACTIVE,
      targetType: MarkerTargetType.RACK,
      targetCode: 'RACK-HCM-A1',
      bindingStatus: 'ACTIVE',
      isActive: true,
      isVisibleInAr: true,
      imageTargetId: 'img-target-rack-a1',
      worldTrackingEnabled: true,
      metadata: { seeded: true },
    },
    {
      markerCode: 'MK-NODE-A1-01',
      displayLabel: 'Node A1-01 Marker',
      lifecycleState: MarkerLifecycleState.ACTIVE,
      targetType: MarkerTargetType.NODE,
      targetCode: 'NODE-HCM-A1-01',
      bindingStatus: 'ACTIVE',
      isActive: true,
      isVisibleInAr: true,
      imageTargetId: 'img-target-node-a101',
      worldTrackingEnabled: true,
      metadata: { seeded: true, scenario: 'golden-path' },
    },
    {
      markerCode: 'MK-B1-PRINT',
      displayLabel: 'Rack B1 Printed Marker',
      lifecycleState: MarkerLifecycleState.PRINTED,
      targetType: MarkerTargetType.RACK,
      targetCode: 'RACK-HCM-B1',
      bindingStatus: 'BOUND_PENDING_VALIDATION',
      isActive: false,
      isVisibleInAr: false,
      worldTrackingEnabled: true,
      metadata: { seeded: true },
    },
    {
      markerCode: 'MK-D1-MOUNT',
      displayLabel: 'Rack D1 Mounted Marker',
      lifecycleState: MarkerLifecycleState.MOUNTED,
      targetType: MarkerTargetType.RACK,
      targetCode: 'RACK-HCM-D1',
      bindingStatus: 'BOUND_PENDING_VALIDATION',
      isActive: false,
      isVisibleInAr: true,
      worldTrackingEnabled: true,
      metadata: { seeded: true },
    },
    {
      markerCode: 'MK-DISC-VALID',
      displayLabel: 'Discovered Node Validated Marker',
      lifecycleState: MarkerLifecycleState.VALIDATED,
      targetType: MarkerTargetType.NODE,
      targetCode: 'NODE-HCM-DISC-01',
      bindingStatus: 'VALIDATED',
      isActive: false,
      isVisibleInAr: true,
      worldTrackingEnabled: true,
      metadata: { seeded: true },
    },
    {
      markerCode: 'MK-REMAPPED-01',
      displayLabel: 'Remapped Marker',
      lifecycleState: MarkerLifecycleState.REMAPPED,
      targetType: MarkerTargetType.NODE,
      targetCode: 'NODE-HCM-B1-01',
      bindingStatus: 'REMAPPED_PENDING_VALIDATION',
      isActive: false,
      isVisibleInAr: true,
      worldTrackingEnabled: true,
      metadata: { seeded: true },
    },
    {
      markerCode: 'MK-RETIRED-01',
      displayLabel: 'Retired Marker',
      lifecycleState: MarkerLifecycleState.RETIRED,
      targetType: MarkerTargetType.RACK,
      targetCode: 'RACK-HCM-C1',
      bindingStatus: 'RETIRED',
      isActive: false,
      isVisibleInAr: false,
      worldTrackingEnabled: true,
      metadata: { seeded: true },
    },
  ],
  nodeRuntimeSnapshots: [
    {
      nodeCode: 'NODE-HCM-A1-01',
      healthState: NodeHealthState.ONLINE,
      heartbeatAt: '2026-06-09T10:00:00.000Z',
      metricsAt: '2026-06-09T10:00:00.000Z',
      cpuUsagePct: 42,
      memoryUsagePct: 63,
      networkRxKbps: 512,
      networkTxKbps: 476,
      activeAlertCount: 0,
      source: 'seed',
      metadata: { seeded: true, scenario: 'golden-path' },
    },
    {
      nodeCode: 'NODE-HCM-D1-01',
      healthState: NodeHealthState.DEGRADED,
      heartbeatAt: '2026-06-09T09:58:00.000Z',
      metricsAt: '2026-06-09T09:58:00.000Z',
      cpuUsagePct: 81,
      memoryUsagePct: 74,
      networkRxKbps: 223,
      networkTxKbps: 199,
      activeAlertCount: 2,
      source: 'seed',
      metadata: { seeded: true },
    },
  ],
};
