export const MONITORING_RULE_REPOSITORY = Symbol('MONITORING_RULE_REPOSITORY');
export const ALERT_REPOSITORY = Symbol('ALERT_REPOSITORY');
export const ALERT_OCCURRENCE_REPOSITORY = Symbol(
  'ALERT_OCCURRENCE_REPOSITORY',
);
export const HEALTH_SUMMARY_REPOSITORY = Symbol('HEALTH_SUMMARY_REPOSITORY');
export const MONITORING_CONTEXT_REPOSITORY = Symbol(
  'MONITORING_CONTEXT_REPOSITORY',
);
export const MONITORING_SNAPSHOT_REPOSITORY = Symbol(
  'MONITORING_SNAPSHOT_REPOSITORY',
);
export const MONITORING_EVENT_PUBLISHER = Symbol('MONITORING_EVENT_PUBLISHER');
