import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, ExternalLink, MapPin, ScanLine, Server } from 'lucide-react-native';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { getNodeContext } from '../../../src/ar/node-context';
import { openWebAr } from '../../../src/ar/open-webar';
import { useAuth } from '../../../src/auth/auth-context';
import { ActionButton } from '../../../src/components/action-button';
import { Screen } from '../../../src/components/screen';
import { useTheme } from '../../../src/theme/theme-context';
import { radii, spacing, type ThemeColors } from '../../../src/theme/tokens';

export default function ArNodeScreen() {
  const { session } = useAuth();
  const params = useLocalSearchParams<{ nodeId?: string; data?: string }>(); const { colors } = useTheme(); const styles = useMemo(() => createStyles(colors), [colors]); const [error, setError] = useState<string | null>(null);
  const nodeId = useMemo(() => decodeURIComponent(Array.isArray(params.nodeId) ? params.nodeId[0] : params.nodeId ?? 'mock-node-001'), [params.nodeId]);
  const data = useMemo(() => { const raw = Array.isArray(params.data) ? params.data[0] : params.data; return raw ? decodeURIComponent(raw) : undefined; }, [params.data]);
  const node = useMemo(() => getNodeContext(nodeId, data), [data, nodeId]);
  async function open(nodeSpecific = true) { setError(null); try { await openWebAr(nodeSpecific ? node.id : undefined, nodeSpecific ? data : undefined, session?.accessToken); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not open the WebAR browser.'); } }
  return <Screen><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><ArrowLeft color={colors.text} size={20} /></Pressable><Text style={styles.headerTitle}>Asset identified</Text><View style={styles.back}><ScanLine color={colors.cyan} size={20} /></View></View><View style={styles.hero}><View style={styles.server}><Server color="#FFFFFF" size={30} /></View><Text style={styles.kicker}>READY FOR WEBAR</Text><Text style={styles.nodeId}>{node.id}</Text><Text style={styles.name}>{node.name}</Text></View><View style={styles.metrics}><Metric icon={MapPin} label="Rack" value={node.rack} /><Metric icon={Server} label="Status" value={node.status.toUpperCase()} /></View><View style={styles.notice}><Text style={styles.noticeTitle}>Browser-based inspection</Text><Text style={styles.noticeText}>WebAR opens in your browser for stable marker tracking on iOS and Android. Return to this app when the inspection is complete.</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}<ActionButton icon={ExternalLink} label="Open WebAR inspection" onPress={() => void open()} /><ActionButton icon={ExternalLink} label="Open WebAR home" variant="secondary" onPress={() => void open(false)} /></Screen>;
  function Metric({ icon: Icon, label, value }: { icon: typeof MapPin; label: string; value: string }) { return <View style={styles.metric}><View style={styles.metricIcon}><Icon color={colors.cyan} size={18} /></View><Text style={styles.metricLabel}>{label}</Text><Text numberOfLines={1} style={styles.metricValue}>{value}</Text></View>; }
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({ header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, back: { alignItems: 'center', justifyContent: 'center', width: 42, height: 42, borderRadius: radii.lg, backgroundColor: colors.panel }, headerTitle: { color: colors.text, fontSize: 15, fontWeight: '900' }, hero: { alignItems: 'center', gap: spacing.sm, padding: spacing.xl, borderRadius: radii.xxl, backgroundColor: colors.hero }, server: { alignItems: 'center', justifyContent: 'center', width: 68, height: 68, marginBottom: spacing.sm, borderRadius: 24, backgroundColor: colors.cyan }, kicker: { color: '#9FB7FF', fontSize: 9, fontWeight: '900', letterSpacing: 1.2 }, nodeId: { color: '#FFFFFF', fontSize: 26, fontWeight: '900' }, name: { color: '#AFC0DF', fontSize: 12 }, metrics: { flexDirection: 'row', gap: spacing.md }, metric: { alignItems: 'center', flex: 1, gap: 5, padding: spacing.lg, borderRadius: radii.xl, backgroundColor: colors.panel }, metricIcon: { alignItems: 'center', justifyContent: 'center', width: 38, height: 38, borderRadius: 14, backgroundColor: colors.cyanSoft }, metricLabel: { color: colors.textMuted, fontSize: 9 }, metricValue: { color: colors.text, fontSize: 13, fontWeight: '900' }, notice: { gap: spacing.sm, padding: spacing.lg, borderRadius: radii.xl, backgroundColor: colors.cyanSoft }, noticeTitle: { color: colors.cyan, fontSize: 13, fontWeight: '900' }, noticeText: { color: colors.textMuted, fontSize: 11, lineHeight: 18 }, error: { color: colors.red, fontSize: 12, fontWeight: '700', textAlign: 'center' } });
