export enum IncidentStatus {
  OPEN = 'OPEN',
  TRIAGED = 'TRIAGED',
  INVESTIGATING = 'INVESTIGATING',
  MITIGATING = 'MITIGATING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}
