export enum TicketActivityType {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  REASSIGNED = 'REASSIGNED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  EVIDENCE_ATTACHED = 'EVIDENCE_ATTACHED',
}
