export const GET_HEALTH_USE_CASE = Symbol('GET_HEALTH_USE_CASE');
export const CREATE_TICKET_USE_CASE = Symbol('CREATE_TICKET_USE_CASE');
export const LIST_TICKETS_USE_CASE = Symbol('LIST_TICKETS_USE_CASE');
export const GET_TICKET_USE_CASE = Symbol('GET_TICKET_USE_CASE');
export const TRANSITION_TICKET_STATUS_USE_CASE = Symbol(
  'TRANSITION_TICKET_STATUS_USE_CASE',
);
export const ASSIGN_TICKET_USE_CASE = Symbol('ASSIGN_TICKET_USE_CASE');
export const ACKNOWLEDGE_TICKET_USE_CASE = Symbol(
  'ACKNOWLEDGE_TICKET_USE_CASE',
);
export const ADD_TICKET_COMMENT_USE_CASE = Symbol(
  'ADD_TICKET_COMMENT_USE_CASE',
);
export const ATTACH_TICKET_EVIDENCE_USE_CASE = Symbol(
  'ATTACH_TICKET_EVIDENCE_USE_CASE',
);
export const CREATE_TICKET_EVIDENCE_UPLOAD_URL_USE_CASE = Symbol(
  'CREATE_TICKET_EVIDENCE_UPLOAD_URL_USE_CASE',
);
export const LIST_TICKET_EVIDENCE_USE_CASE = Symbol(
  'LIST_TICKET_EVIDENCE_USE_CASE',
);
export const CREATE_INCIDENT_USE_CASE = Symbol('CREATE_INCIDENT_USE_CASE');
export const LIST_INCIDENTS_USE_CASE = Symbol('LIST_INCIDENTS_USE_CASE');
export const GET_INCIDENT_USE_CASE = Symbol('GET_INCIDENT_USE_CASE');
