export const ASSET_SERVICE_CLIENT = Symbol('ASSET_SERVICE_CLIENT');
export const MONITORING_SERVICE_CLIENT = Symbol('MONITORING_SERVICE_CLIENT');
export const INCIDENT_WORKFLOW_SERVICE_CLIENT = Symbol(
  'INCIDENT_WORKFLOW_SERVICE_CLIENT',
);
