apiVersion: 1

contactPoints:
  - orgId: 1
    name: lab-external-alertmanager
    receivers:
      - uid: lab_external_alertmanager
        type: prometheus-alertmanager
        disableResolveMessage: false
        settings:
          url: http://alertmanager:9093

policies:
  - orgId: 1
    receiver: lab-external-alertmanager
    group_by:
      - "..."
    group_wait: 0s
    group_interval: 30s
    repeat_interval: 4h
