input:
  kafka:
    addresses:
      - redpanda:9092
    topics:
      - telemetry.normalized.received
    consumer_group: redpanda-connect-group

pipeline:
  processors:
    - log:
        level: INFO
        message: "received message: ${!content()}"

output:
  sql_insert:
    driver: "clickhouse"
    # Chuỗi kết nối tới ClickHouse sử dụng giao thức Native Port (8123)
    dsn: "clickhouse://root:password@clickhouse:9000/telemetry_db"
    table: "normalized_telemetry_queue"
    columns:
      - "payload"
    # Đưa toàn bộ nội dung tin nhắn dạng String vào cột payload
    args_mapping: |
      root = [ this.string() ]
    max_in_flight: 64
    batching:
      count: 1000 # Gom tối đa 1000 tin nhắn
      period: "1s" # Hoặc đẩy sau mỗi 1 giây