services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    ports:
      - "5555:80"
      - "443:443"
      - "8081:8081"
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.network=edge
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - edge

networks:
  edge:
    name: edge
