packages:
  - "control-plane/*"
  - "data-plane/*"
  - "ingestion-worker"
  - "shared"

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  bcrypt: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "bcrypt"
