// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/telemetry/v1/telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Agent         *AgentMeta             `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Batch         *BatchMeta             `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"`
	Context       *PayloadContext        `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Metrics       []*MetricRecord        `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchRequest) Reset() {
	*x = IngestBatchRequest{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchRequest) ProtoMessage() {}

func (x *IngestBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *IngestBatchRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *IngestBatchRequest) GetAgent() *AgentMeta {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *IngestBatchRequest) GetBatch() *BatchMeta {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *IngestBatchRequest) GetContext() *PayloadContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *IngestBatchRequest) GetMetrics() []*MetricRecord {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type AgentMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	StartedAt     string                 `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMeta) Reset() {
	*x = AgentMeta{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMeta) ProtoMessage() {}

func (x *AgentMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMeta.ProtoReflect.Descriptor instead.
func (*AgentMeta) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMeta) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMeta) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentMeta) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AgentMeta) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentMeta) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentMeta) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

type BatchMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	CollectedAt   string                 `protobuf:"bytes,3,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	SentAt        string                 `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	RecordCount   int32                  `protobuf:"varint,5,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	DroppedCount  int32                  `protobuf:"varint,6,opt,name=dropped_count,json=droppedCount,proto3" json:"dropped_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMeta) Reset() {
	*x = BatchMeta{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMeta) ProtoMessage() {}

func (x *BatchMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMeta.ProtoReflect.Descriptor instead.
func (*BatchMeta) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *BatchMeta) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchMeta) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *BatchMeta) GetCollectedAt() string {
	if x != nil {
		return x.CollectedAt
	}
	return ""
}

func (x *BatchMeta) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *BatchMeta) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *BatchMeta) GetDroppedCount() int32 {
	if x != nil {
		return x.DroppedCount
	}
	return 0
}

type PayloadContext struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Identity            *ContextIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	HardwareFingerprint *HardwareFingerprint   `protobuf:"bytes,2,opt,name=hardware_fingerprint,json=hardwareFingerprint,proto3" json:"hardware_fingerprint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PayloadContext) Reset() {
	*x = PayloadContext{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadContext) ProtoMessage() {}

func (x *PayloadContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadContext.ProtoReflect.Descriptor instead.
func (*PayloadContext) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *PayloadContext) GetIdentity() *ContextIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PayloadContext) GetHardwareFingerprint() *HardwareFingerprint {
	if x != nil {
		return x.HardwareFingerprint
	}
	return nil
}

type ContextIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	DeviceType    string                 `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextIdentity) Reset() {
	*x = ContextIdentity{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextIdentity) ProtoMessage() {}

func (x *ContextIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextIdentity.ProtoReflect.Descriptor instead.
func (*ContextIdentity) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *ContextIdentity) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ContextIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ContextIdentity) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContextIdentity) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

type HardwareFingerprint struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrimaryIpv4      string                 `protobuf:"bytes,1,opt,name=primary_ipv4,json=primaryIpv4,proto3" json:"primary_ipv4,omitempty"`
	MacAddress       string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	HardwareSerial   string                 `protobuf:"bytes,3,opt,name=hardware_serial,json=hardwareSerial,proto3" json:"hardware_serial,omitempty"`
	OsProduct        string                 `protobuf:"bytes,4,opt,name=os_product,json=osProduct,proto3" json:"os_product,omitempty"`
	LogicalCpuCount  string                 `protobuf:"bytes,5,opt,name=logical_cpu_count,json=logicalCpuCount,proto3" json:"logical_cpu_count,omitempty"`
	CpuArchitecture  string                 `protobuf:"bytes,6,opt,name=cpu_architecture,json=cpuArchitecture,proto3" json:"cpu_architecture,omitempty"`
	MotherboardModel string                 `protobuf:"bytes,7,opt,name=motherboard_model,json=motherboardModel,proto3" json:"motherboard_model,omitempty"`
	CpuModel         string                 `protobuf:"bytes,8,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	GpuModelPrimary  string                 `protobuf:"bytes,9,opt,name=gpu_model_primary,json=gpuModelPrimary,proto3" json:"gpu_model_primary,omitempty"`
	SsdModelPrimary  string                 `protobuf:"bytes,10,opt,name=ssd_model_primary,json=ssdModelPrimary,proto3" json:"ssd_model_primary,omitempty"`
	BatteryModel     string                 `protobuf:"bytes,11,opt,name=battery_model,json=batteryModel,proto3" json:"battery_model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HardwareFingerprint) Reset() {
	*x = HardwareFingerprint{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareFingerprint) ProtoMessage() {}

func (x *HardwareFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareFingerprint.ProtoReflect.Descriptor instead.
func (*HardwareFingerprint) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *HardwareFingerprint) GetPrimaryIpv4() string {
	if x != nil {
		return x.PrimaryIpv4
	}
	return ""
}

func (x *HardwareFingerprint) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *HardwareFingerprint) GetHardwareSerial() string {
	if x != nil {
		return x.HardwareSerial
	}
	return ""
}

func (x *HardwareFingerprint) GetOsProduct() string {
	if x != nil {
		return x.OsProduct
	}
	return ""
}

func (x *HardwareFingerprint) GetLogicalCpuCount() string {
	if x != nil {
		return x.LogicalCpuCount
	}
	return ""
}

func (x *HardwareFingerprint) GetCpuArchitecture() string {
	if x != nil {
		return x.CpuArchitecture
	}
	return ""
}

func (x *HardwareFingerprint) GetMotherboardModel() string {
	if x != nil {
		return x.MotherboardModel
	}
	return ""
}

func (x *HardwareFingerprint) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *HardwareFingerprint) GetGpuModelPrimary() string {
	if x != nil {
		return x.GpuModelPrimary
	}
	return ""
}

func (x *HardwareFingerprint) GetSsdModelPrimary() string {
	if x != nil {
		return x.SsdModelPrimary
	}
	return ""
}

func (x *HardwareFingerprint) GetBatteryModel() string {
	if x != nil {
		return x.BatteryModel
	}
	return ""
}

type MetricRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricKey     string                 `protobuf:"bytes,1,opt,name=metric_key,json=metricKey,proto3" json:"metric_key,omitempty"`
	ScopeType     string                 `protobuf:"bytes,2,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	ScopeId       string                 `protobuf:"bytes,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	SourceMetric  string                 `protobuf:"bytes,8,opt,name=source_metric,json=sourceMetric,proto3" json:"source_metric,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRecord) Reset() {
	*x = MetricRecord{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRecord) ProtoMessage() {}

func (x *MetricRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRecord.ProtoReflect.Descriptor instead.
func (*MetricRecord) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *MetricRecord) GetMetricKey() string {
	if x != nil {
		return x.MetricKey
	}
	return ""
}

func (x *MetricRecord) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *MetricRecord) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *MetricRecord) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetricRecord) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MetricRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MetricRecord) GetSourceMetric() string {
	if x != nil {
		return x.SourceMetric
	}
	return ""
}

func (x *MetricRecord) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type IngestBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	EnvelopeId    string                 `protobuf:"bytes,2,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchResponse) Reset() {
	*x = IngestBatchResponse{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchResponse) ProtoMessage() {}

func (x *IngestBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *IngestBatchResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestBatchResponse) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

func (x *IngestBatchResponse) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

var File_api_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_api_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	" api/telemetry/v1/telemetry.proto\x12\x10api.telemetry.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x97\x02\n" +
	"\x12IngestBatchRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x121\n" +
	"\x05agent\x18\x02 \x01(\v2\x1b.api.telemetry.v1.AgentMetaR\x05agent\x121\n" +
	"\x05batch\x18\x03 \x01(\v2\x1b.api.telemetry.v1.BatchMetaR\x05batch\x12:\n" +
	"\acontext\x18\x04 \x01(\v2 .api.telemetry.v1.PayloadContextR\acontext\x128\n" +
	"\ametrics\x18\x05 \x03(\v2\x1e.api.telemetry.v1.MetricRecordR\ametrics\"\xc6\x01\n" +
	"\tAgentMeta\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\tR\tstartedAt\"\xc6\x01\n" +
	"\tBatchMeta\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12!\n" +
	"\fcollected_at\x18\x03 \x01(\tR\vcollectedAt\x12\x17\n" +
	"\asent_at\x18\x04 \x01(\tR\x06sentAt\x12!\n" +
	"\frecord_count\x18\x05 \x01(\x05R\vrecordCount\x12#\n" +
	"\rdropped_count\x18\x06 \x01(\x05R\fdroppedCount\"\xa9\x01\n" +
	"\x0ePayloadContext\x12=\n" +
	"\bidentity\x18\x01 \x01(\v2!.api.telemetry.v1.ContextIdentityR\bidentity\x12X\n" +
	"\x14hardware_fingerprint\x18\x02 \x01(\v2%.api.telemetry.v1.HardwareFingerprintR\x13hardwareFingerprint\"\x7f\n" +
	"\x0fContextIdentity\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1f\n" +
	"\vdevice_type\x18\x04 \x01(\tR\n" +
	"deviceType\"\xbf\x03\n" +
	"\x13HardwareFingerprint\x12!\n" +
	"\fprimary_ipv4\x18\x01 \x01(\tR\vprimaryIpv4\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12'\n" +
	"\x0fhardware_serial\x18\x03 \x01(\tR\x0ehardwareSerial\x12\x1d\n" +
	"\n" +
	"os_product\x18\x04 \x01(\tR\tosProduct\x12*\n" +
	"\x11logical_cpu_count\x18\x05 \x01(\tR\x0flogicalCpuCount\x12)\n" +
	"\x10cpu_architecture\x18\x06 \x01(\tR\x0fcpuArchitecture\x12+\n" +
	"\x11motherboard_model\x18\a \x01(\tR\x10motherboardModel\x12\x1b\n" +
	"\tcpu_model\x18\b \x01(\tR\bcpuModel\x12*\n" +
	"\x11gpu_model_primary\x18\t \x01(\tR\x0fgpuModelPrimary\x12*\n" +
	"\x11ssd_model_primary\x18\n" +
	" \x01(\tR\x0fssdModelPrimary\x12#\n" +
	"\rbattery_model\x18\v \x01(\tR\fbatteryModel\"\xfb\x02\n" +
	"\fMetricRecord\x12\x1d\n" +
	"\n" +
	"metric_key\x18\x01 \x01(\tR\tmetricKey\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x02 \x01(\tR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\x03 \x01(\tR\ascopeId\x12,\n" +
	"\x05value\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12#\n" +
	"\rsource_metric\x18\b \x01(\tR\fsourceMetric\x12<\n" +
	"\x04tags\x18\t \x03(\v2(.api.telemetry.v1.MetricRecord.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x13IngestBatchResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\venvelope_id\x18\x02 \x01(\tR\n" +
	"envelopeId\x12\x1f\n" +
	"\vreceived_at\x18\x03 \x01(\tR\n" +
	"receivedAt2t\n" +
	"\x16TelemetryIngestService\x12Z\n" +
	"\vIngestBatch\x12$.api.telemetry.v1.IngestBatchRequest\x1a%.api.telemetry.v1.IngestBatchResponseB Z\x1e./api/telemetry/v1;telemetrypbb\x06proto3"

var (
	file_api_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_api_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_api_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_api_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_api_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_telemetry_v1_telemetry_proto_rawDesc), len(file_api_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_api_telemetry_v1_telemetry_proto_rawDescData
}

var file_api_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_telemetry_v1_telemetry_proto_goTypes = []any{
	(*IngestBatchRequest)(nil),  // 0: api.telemetry.v1.IngestBatchRequest
	(*AgentMeta)(nil),           // 1: api.telemetry.v1.AgentMeta
	(*BatchMeta)(nil),           // 2: api.telemetry.v1.BatchMeta
	(*PayloadContext)(nil),      // 3: api.telemetry.v1.PayloadContext
	(*ContextIdentity)(nil),     // 4: api.telemetry.v1.ContextIdentity
	(*HardwareFingerprint)(nil), // 5: api.telemetry.v1.HardwareFingerprint
	(*MetricRecord)(nil),        // 6: api.telemetry.v1.MetricRecord
	(*IngestBatchResponse)(nil), // 7: api.telemetry.v1.IngestBatchResponse
	nil,                         // 8: api.telemetry.v1.MetricRecord.TagsEntry
	(*structpb.Value)(nil),      // 9: google.protobuf.Value
}
var file_api_telemetry_v1_telemetry_proto_depIdxs = []int32{
	1, // 0: api.telemetry.v1.IngestBatchRequest.agent:type_name -> api.telemetry.v1.AgentMeta
	2, // 1: api.telemetry.v1.IngestBatchRequest.batch:type_name -> api.telemetry.v1.BatchMeta
	3, // 2: api.telemetry.v1.IngestBatchRequest.context:type_name -> api.telemetry.v1.PayloadContext
	6, // 3: api.telemetry.v1.IngestBatchRequest.metrics:type_name -> api.telemetry.v1.MetricRecord
	4, // 4: api.telemetry.v1.PayloadContext.identity:type_name -> api.telemetry.v1.ContextIdentity
	5, // 5: api.telemetry.v1.PayloadContext.hardware_fingerprint:type_name -> api.telemetry.v1.HardwareFingerprint
	9, // 6: api.telemetry.v1.MetricRecord.value:type_name -> google.protobuf.Value
	8, // 7: api.telemetry.v1.MetricRecord.tags:type_name -> api.telemetry.v1.MetricRecord.TagsEntry
	0, // 8: api.telemetry.v1.TelemetryIngestService.IngestBatch:input_type -> api.telemetry.v1.IngestBatchRequest
	7, // 9: api.telemetry.v1.TelemetryIngestService.IngestBatch:output_type -> api.telemetry.v1.IngestBatchResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_telemetry_v1_telemetry_proto_init() }
func file_api_telemetry_v1_telemetry_proto_init() {
	if File_api_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_telemetry_v1_telemetry_proto_rawDesc), len(file_api_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_api_telemetry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_api_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_api_telemetry_v1_telemetry_proto = out.File
	file_api_telemetry_v1_telemetry_proto_goTypes = nil
	file_api_telemetry_v1_telemetry_proto_depIdxs = nil
}
