"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCode = void 0;
var ErrorCode;
(function (ErrorCode) {
    ErrorCode["UNAUTHENTICATED"] = "UNAUTHENTICATED";
    ErrorCode["PERMISSION_DENIED"] = "PERMISSION_DENIED";
    ErrorCode["CONFLICT"] = "CONFLICT";
    ErrorCode["NOT_FOUND"] = "NOT_FOUND";
    ErrorCode["INVALID_ARGUMENT"] = "INVALID_ARGUMENT";
    ErrorCode["INTERNAL"] = "INTERNAL";
    ErrorCode["ASSET_RACK_NOT_FOUND"] = "ASSET_RACK_NOT_FOUND";
    ErrorCode["ASSET_SWITCH_NOT_FOUND"] = "ASSET_SWITCH_NOT_FOUND";
    ErrorCode["ASSET_NODE_NOT_FOUND"] = "ASSET_NODE_NOT_FOUND";
    ErrorCode["ASSET_SERVICE_NOT_FOUND"] = "ASSET_SERVICE_NOT_FOUND";
    ErrorCode["ASSET_CONTAINER_NOT_FOUND"] = "ASSET_CONTAINER_NOT_FOUND";
    ErrorCode["ASSET_MARKER_NOT_FOUND"] = "ASSET_MARKER_NOT_FOUND";
    ErrorCode["ASSET_MARKER_NOT_ACTIVE"] = "ASSET_MARKER_NOT_ACTIVE";
    ErrorCode["ASSET_MARKER_ALREADY_MAPPED"] = "ASSET_MARKER_ALREADY_MAPPED";
    ErrorCode["ASSET_MARKER_TARGET_INVALID"] = "ASSET_MARKER_TARGET_INVALID";
    ErrorCode["ASSET_CODE_CONFLICT"] = "ASSET_CODE_CONFLICT";
    ErrorCode["ASSET_PARENT_INVALID"] = "ASSET_PARENT_INVALID";
    ErrorCode["ASSET_NODE_ALREADY_ASSIGNED"] = "ASSET_NODE_ALREADY_ASSIGNED";
    ErrorCode["ASSET_INVENTORY_SOURCE_NODE_UNREGISTERED"] = "ASSET_INVENTORY_SOURCE_NODE_UNREGISTERED";
    ErrorCode["ASSET_TOPOLOGY_RELATION_INVALID"] = "ASSET_TOPOLOGY_RELATION_INVALID";
})(ErrorCode || (exports.ErrorCode = ErrorCode = {}));
//# sourceMappingURL=error-code.enum.js.map
