// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/registration/v1/registration.proto

package registrationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HardwareInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrimaryIpv4     string                 `protobuf:"bytes,1,opt,name=primary_ipv4,json=primaryIpv4,proto3" json:"primary_ipv4,omitempty"`
	MacAddress      string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	HardwareSerial  string                 `protobuf:"bytes,3,opt,name=hardware_serial,json=hardwareSerial,proto3" json:"hardware_serial,omitempty"`
	Vendor          string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model           string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	OsProduct       string                 `protobuf:"bytes,6,opt,name=os_product,json=osProduct,proto3" json:"os_product,omitempty"`
	LogicalCpuCount int32                  `protobuf:"varint,7,opt,name=logical_cpu_count,json=logicalCpuCount,proto3" json:"logical_cpu_count,omitempty"`
	CpuArchitecture string                 `protobuf:"bytes,8,opt,name=cpu_architecture,json=cpuArchitecture,proto3" json:"cpu_architecture,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_api_registration_v1_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_v1_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_api_registration_v1_registration_proto_rawDescGZIP(), []int{0}
}

func (x *HardwareInfo) GetPrimaryIpv4() string {
	if x != nil {
		return x.PrimaryIpv4
	}
	return ""
}

func (x *HardwareInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *HardwareInfo) GetHardwareSerial() string {
	if x != nil {
		return x.HardwareSerial
	}
	return ""
}

func (x *HardwareInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *HardwareInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HardwareInfo) GetOsProduct() string {
	if x != nil {
		return x.OsProduct
	}
	return ""
}

func (x *HardwareInfo) GetLogicalCpuCount() int32 {
	if x != nil {
		return x.LogicalCpuCount
	}
	return 0
}

func (x *HardwareInfo) GetCpuArchitecture() string {
	if x != nil {
		return x.CpuArchitecture
	}
	return ""
}

type RegisterNodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BootstrapToken  string                 `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DeviceType      string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DiscoverySource string                 `protobuf:"bytes,4,opt,name=discovery_source,json=discoverySource,proto3" json:"discovery_source,omitempty"`
	HardwareInfo    *HardwareInfo          `protobuf:"bytes,5,opt,name=hardware_info,json=hardwareInfo,proto3" json:"hardware_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_api_registration_v1_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_v1_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_registration_v1_registration_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *RegisterNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterNodeRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *RegisterNodeRequest) GetDiscoverySource() string {
	if x != nil {
		return x.DiscoverySource
	}
	return ""
}

func (x *RegisterNodeRequest) GetHardwareInfo() *HardwareInfo {
	if x != nil {
		return x.HardwareInfo
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`                 // Chuỗi PEM chứa chứng chỉ X.509
	PrivateKey    []byte                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // Chuỗi PEM chứa khóa riêng RSA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_api_registration_v1_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_v1_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_registration_v1_registration_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterNodeResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RegisterNodeResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

var File_api_registration_v1_registration_proto protoreflect.FileDescriptor

const file_api_registration_v1_registration_proto_rawDesc = "" +
	"\n" +
	"&api/registration/v1/registration.proto\x12\x13api.registration.v1\"\x9f\x02\n" +
	"\fHardwareInfo\x12!\n" +
	"\fprimary_ipv4\x18\x01 \x01(\tR\vprimaryIpv4\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12'\n" +
	"\x0fhardware_serial\x18\x03 \x01(\tR\x0ehardwareSerial\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"os_product\x18\x06 \x01(\tR\tosProduct\x12*\n" +
	"\x11logical_cpu_count\x18\a \x01(\x05R\x0flogicalCpuCount\x12)\n" +
	"\x10cpu_architecture\x18\b \x01(\tR\x0fcpuArchitecture\"\xee\x01\n" +
	"\x13RegisterNodeRequest\x12'\n" +
	"\x0fbootstrap_token\x18\x01 \x01(\tR\x0ebootstrapToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12)\n" +
	"\x10discovery_source\x18\x04 \x01(\tR\x0fdiscoverySource\x12F\n" +
	"\rhardware_info\x18\x05 \x01(\v2!.api.registration.v1.HardwareInfoR\fhardwareInfo\"t\n" +
	"\x14RegisterNodeResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\vcertificate\x18\x02 \x01(\fR\vcertificate\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\fR\n" +
	"privateKey2z\n" +
	"\x13RegistrationService\x12c\n" +
	"\fRegisterNode\x12(.api.registration.v1.RegisterNodeRequest\x1a).api.registration.v1.RegisterNodeResponseB&Z$./api/registration/v1;registrationpbb\x06proto3"

var (
	file_api_registration_v1_registration_proto_rawDescOnce sync.Once
	file_api_registration_v1_registration_proto_rawDescData []byte
)

func file_api_registration_v1_registration_proto_rawDescGZIP() []byte {
	file_api_registration_v1_registration_proto_rawDescOnce.Do(func() {
		file_api_registration_v1_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_registration_v1_registration_proto_rawDesc), len(file_api_registration_v1_registration_proto_rawDesc)))
	})
	return file_api_registration_v1_registration_proto_rawDescData
}

var file_api_registration_v1_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_registration_v1_registration_proto_goTypes = []any{
	(*HardwareInfo)(nil),         // 0: api.registration.v1.HardwareInfo
	(*RegisterNodeRequest)(nil),  // 1: api.registration.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 2: api.registration.v1.RegisterNodeResponse
}
var file_api_registration_v1_registration_proto_depIdxs = []int32{
	0, // 0: api.registration.v1.RegisterNodeRequest.hardware_info:type_name -> api.registration.v1.HardwareInfo
	1, // 1: api.registration.v1.RegistrationService.RegisterNode:input_type -> api.registration.v1.RegisterNodeRequest
	2, // 2: api.registration.v1.RegistrationService.RegisterNode:output_type -> api.registration.v1.RegisterNodeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_registration_v1_registration_proto_init() }
func file_api_registration_v1_registration_proto_init() {
	if File_api_registration_v1_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_registration_v1_registration_proto_rawDesc), len(file_api_registration_v1_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_registration_v1_registration_proto_goTypes,
		DependencyIndexes: file_api_registration_v1_registration_proto_depIdxs,
		MessageInfos:      file_api_registration_v1_registration_proto_msgTypes,
	}.Build()
	File_api_registration_v1_registration_proto = out.File
	file_api_registration_v1_registration_proto_goTypes = nil
	file_api_registration_v1_registration_proto_depIdxs = nil
}
