apiVersion: v1
kind: ConfigMap
metadata:
  name: asset-service-config
  namespace: ar-monitoring-dev
data:
  NODE_ENV: production
  PORT: "4002"
  SWAGGER_ENABLED: "false"
  MONGODB_SERVER_SELECTION_TIMEOUT_MS: "5000"
  MONGODB_RETRY_ATTEMPTS: "1"
  MONGODB_RETRY_DELAY_MS: "1000"
