apiVersion: v1
kind: Service
metadata:
  name: asset-service
  namespace: ar-monitoring-dev
  labels:
    app.kubernetes.io/name: asset-service
    app.kubernetes.io/part-of: ar-monitoring
spec:
  selector:
    app.kubernetes.io/name: asset-service
  ports:
    - name: http
      port: 4002
      targetPort: http
