export const RACK_REPOSITORY = Symbol('RACK_REPOSITORY');
export const NODE_REPOSITORY = Symbol('NODE_REPOSITORY');
export const MARKER_REPOSITORY = Symbol('MARKER_REPOSITORY');
export const NODE_RUNTIME_SNAPSHOT_REPOSITORY = Symbol(
  'NODE_RUNTIME_SNAPSHOT_REPOSITORY',
);
export const DISCOVERED_NODE_REPOSITORY = Symbol('DISCOVERED_NODE_REPOSITORY');
export const ASSET_QUERY_CACHE = Symbol('ASSET_QUERY_CACHE');
export const NODE_MAPPING_EVENT_PUBLISHER = Symbol(
  'NODE_MAPPING_EVENT_PUBLISHER',
);
