-- =========================================================
-- FILE NAME: 01_metric_profile.sql
-- MUC DICH:
--   Khai bao bang cau hinh metric_profile va dictionary
--   dict_metric_profile dung de tra cuu policy theo runtime.
-- TANG DU LIEU PHUC VU:
--   03_reference_policy / semantic contract / policy runtime lookup
-- GHI CHU:
--   Dictionary nay dung de cac view o cac tang current-live,
--   aggregate 1m, aggregate 5m, rack summary... co the tra cuu
--   policy bang dictGet thay vi hardcode multiIf lap lai.
-- =========================================================

USE telemetry_db;

-- Bang cau hinh metric profile la source-of-truth cho:
-- semantic class, freshness, threshold, override, preferred aggregation.

DROP TABLE IF EXISTS metric_profile;
CREATE TABLE IF NOT EXISTS metric_profile
(
    scope_type String,
    metric_key String,

    metric_label String DEFAULT '',
    description String DEFAULT '',

    value_kind Enum8(
        'numeric' = 1,
        'text' = 2,
        'state' = 3
    ),

    semantic_class String,
    directionality String,

    is_enabled UInt8 DEFAULT 1,
    is_operational_metric UInt8 DEFAULT 0,
    is_ranking_metric UInt8 DEFAULT 0,
    override_on_critical UInt8 DEFAULT 0,

    freshness_profile String DEFAULT 'realtime',
    fresh_after_sec UInt32 DEFAULT 30,
    stale_after_sec UInt32 DEFAULT 120,

    warning_operator String DEFAULT '',
    warning_threshold_numeric Nullable(Float64),
    critical_operator String DEFAULT '',
    critical_threshold_numeric Nullable(Float64),

    warning_text_values Array(String) DEFAULT [],
    critical_text_values Array(String) DEFAULT [],

    preferred_spatial_agg String DEFAULT '',
    preferred_temporal_agg_1m String DEFAULT '',
    preferred_temporal_agg_5m String DEFAULT '',
    preferred_summary_agg String DEFAULT '',

    preferred_numeric_field String DEFAULT '',
    preferred_text_field String DEFAULT '',

    notes String DEFAULT '',
    policy_version UInt32 DEFAULT 1,
    updated_at DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (scope_type, metric_key);

-- Dictionary dict_metric_profile doc policy vao RAM de query-time lookup.
-- Chu y:
-- 1. Khoa cua policy hien tai la (scope_type, metric_key), deu la String.
-- 2. Vi vay dung COMPLEX_KEY_HASHED phu hop hon HASHED_2D cho composite string key.
-- 3. View phia tren nen uu tien dictGet / dictGetOrDefault de lay policy
--    thay vi hardcode threshold va semantic mapping bang multiIf.
DROP DICTIONARY IF EXISTS dict_metric_profile;

CREATE DICTIONARY IF NOT EXISTS dict_metric_profile (
    scope_type String,
    metric_key String,
    metric_label String,
    description String,
    value_kind String,
    semantic_class String,
    directionality String,
    is_enabled UInt8,
    is_operational_metric UInt8,
    is_ranking_metric UInt8,
    override_on_critical UInt8,
    freshness_profile String,
    fresh_after_sec UInt32,
    stale_after_sec UInt32,
    warning_operator String,
    warning_threshold_numeric Nullable (Float64),
    critical_operator String,
    critical_threshold_numeric Nullable (Float64),
    warning_text_values Array(String),
    critical_text_values Array(String),
    preferred_spatial_agg String,
    preferred_temporal_agg_1m String,
    preferred_temporal_agg_5m String,
    preferred_summary_agg String,
    preferred_numeric_field String,
    preferred_text_field String,
    notes String,
    policy_version UInt32,
    updated_at DateTime
) PRIMARY KEY scope_type,
metric_key SOURCE (
    CLICKHOUSE (
        HOST 'localhost' PORT 9000 USER 'root' PASSWORD 'password' DB 'telemetry_db'
        QUERY '
            SELECT
                scope_type,
                metric_key,
                metric_label,
                description,
                toString(value_kind) AS value_kind,
                semantic_class,
                directionality,
                is_enabled,
                is_operational_metric,
                is_ranking_metric,
                override_on_critical,
                freshness_profile,
                fresh_after_sec,
                stale_after_sec,
                warning_operator,
                warning_threshold_numeric,
                critical_operator,
                critical_threshold_numeric,
                warning_text_values,
                critical_text_values,
                preferred_spatial_agg,
                preferred_temporal_agg_1m,
                preferred_temporal_agg_5m,
                preferred_summary_agg,
                preferred_numeric_field,
                preferred_text_field,
                notes,
                policy_version,
                updated_at
            FROM telemetry_db.metric_profile
        '
    )
) LAYOUT (COMPLEX_KEY_HASHED ()) LIFETIME (MIN 1 MAX 60);

-- Seed policy MVP cho node metrics.
INSERT INTO metric_profile
(
    scope_type,
    metric_key,
    metric_label,
    description,
    value_kind,
    semantic_class,
    directionality,
    is_enabled,
    is_operational_metric,
    is_ranking_metric,
    override_on_critical,
    freshness_profile,
    fresh_after_sec,
    stale_after_sec,
    warning_operator,
    warning_threshold_numeric,
    critical_operator,
    critical_threshold_numeric,
    warning_text_values,
    critical_text_values,
    preferred_spatial_agg,
    preferred_temporal_agg_1m,
    preferred_temporal_agg_5m,
    preferred_summary_agg,
    preferred_numeric_field,
    preferred_text_field,
    notes,
    policy_version
)
VALUES
(
    'node',
    'agent.heartbeat',
    'Agent Heartbeat',
    'Collector heartbeat signal used to determine collector liveness for the node.',
    'state',
    'state',
    'stateful',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'latest',
    'text_last',
    'text_last',
    'latest',
    '',
    'latest_value_text',
    'Collector liveness heartbeat retained in serving views so monitoring can reason about ONLINE/OFFLINE separately from resource metrics.',
    1
),
(
    'node',
    'node.cpu_usage_pct',
    'CPU Usage',
    'Current CPU utilization used for node severity, rack ranking, and trend analysis.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    85,
    '>=',
    95,
    [],
    [],
    'max',
    'p95',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Core operator-first utilization metric.',
    1
),
(
    'node',
    'node.memory_used_pct',
    'Memory Usage',
    'Current memory utilization used for node severity, rack ranking, and trend analysis.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    85,
    '>=',
    95,
    [],
    [],
    'max',
    'p95',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Core operator-first utilization metric.',
    1
),
(
    'node',
    'node.memory_available_mb',
    'Available Memory',
    'Supporting context metric for memory pressure diagnosis.',
    'numeric',
    'utilization',
    'lower_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'min',
    'min',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Useful for diagnosis but not primary ranking signal.',
    1
),
(
    'node',
    'node.memory_commit_used_pct',
    'Memory Commit Usage',
    'Additional memory pressure signal for diagnosis.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'p95',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Secondary memory pressure context.',
    1
),
(
    'node',
    'node.disk_used_pct',
    'Disk Usage',
    'Disk utilization percent. Worst volume should dominate node and rack view.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    85,
    '>=',
    95,
    [],
    [],
    'max',
    'max',
    'max',
    'max',
    'latest_value_numeric',
    '',
    'Volume-level metric where worst series matters.',
    1
),
(
    'node',
    'node.disk_free_gb',
    'Disk Free Capacity',
    'Supporting storage capacity context metric.',
    'numeric',
    'utilization',
    'lower_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'min',
    'min',
    'avg',
    'min',
    'latest_value_numeric',
    '',
    'Useful for diagnosis and capacity context.',
    1
),
(
    'node',
    'node.network_rx_bytes_sec',
    'Network RX Throughput',
    'Inbound throughput used mainly for activity and trend, not direct severity.',
    'numeric',
    'utilization',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    'avg',
    'avg',
    'sum',
    'latest_value_numeric',
    '',
    'High throughput is contextual and should not directly imply bad state.',
    1
),
(
    'node',
    'node.network_tx_bytes_sec',
    'Network TX Throughput',
    'Outbound throughput used mainly for activity and trend, not direct severity.',
    'numeric',
    'utilization',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    'avg',
    'avg',
    'sum',
    'latest_value_numeric',
    '',
    'High throughput is contextual and should not directly imply bad state.',
    1
),
(
    'node',
    'node.network_utilization_pct',
    'Network Utilization',
    'Relative network saturation signal.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'p95',
    'avg',
    'max',
    'latest_value_numeric',
    '',
    'Potential future ranking signal if network saturation becomes important.',
    1
),
(
    'node',
    'node.primary_nic_status',
    'Primary NIC Status',
    'Primary network interface state used for availability and ranking override.',
    'state',
    'state',
    'stateful',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    ['dormant', 'lowerlayerdown'],
    ['down', 'notpresent', 'disconnected'],
    'worst_state',
    'text_last',
    'text_last',
    'latest',
    '',
    'latest_value_text',
    'State metric with explicit text-based severity mapping.',
    1
),
(
    'node',
    'node.uptime_seconds',
    'Uptime',
    'Host uptime used as current state context, not a direct ranking signal.',
    'state',
    'state',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'latest',
    'latest',
    'latest',
    'latest',
    'latest_value_numeric',
    '',
    'State-like metric kept for operational context.',
    1
),
(
    'node',
    'node.cpu_queue_length',
    'CPU Queue Length',
    'CPU contention symptom with strong triage value.',
    'numeric',
    'symptom',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    4,
    '>=',
    10,
    [],
    [],
    'max',
    'max',
    'p95',
    'max',
    'latest_value_numeric',
    '',
    'Symptom metric useful for ranking and override.',
    1
),
(
    'node',
    'node.disk_queue_length',
    'Disk Queue Length',
    'Storage contention symptom with strong triage value.',
    'numeric',
    'symptom',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    2,
    '>=',
    5,
    [],
    [],
    'max',
    'max',
    'p95',
    'max',
    'latest_value_numeric',
    '',
    'Symptom metric useful for ranking and override.',
    1
),
(
    'node',
    'node.memory_page_faults_rate',
    'Memory Page Fault Rate',
    'Memory pressure symptom useful for degradation analysis.',
    'numeric',
    'symptom',
    'higher_is_worse',
    1,
    1,
    1,
    0,
    'realtime',
    30,
    120,
    '>=',
    5000,
    '>=',
    20000,
    [],
    [],
    'max',
    'max',
    'p95',
    'max',
    'latest_value_numeric',
    '',
    'Warning/critical thresholds follow current hardcoded policy.',
    1
),
(
    'node',
    'node.tcp_retransmit_pct',
    'TCP Retransmit Percent',
    'Network fault symptom useful for ranking and degradation analysis.',
    'numeric',
    'symptom',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    1,
    '>=',
    5,
    [],
    [],
    'max',
    'max',
    'p95',
    'max',
    'latest_value_numeric',
    '',
    'Strong signal for network quality degradation.',
    1
),
(
    'node',
    'node.tcp_connection_failures_rate',
    'TCP Connection Failures Rate',
    'Connection failure symptom for triage and fault indication.',
    'numeric',
    'symptom',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '>',
    0,
    '>',
    10,
    [],
    [],
    'max',
    'max',
    'p95',
    'max',
    'latest_value_numeric',
    '',
    'Useful symptom but not configured as critical override in current policy.',
    1
),
(
    'node',
    'node.cpu_dpc_rate',
    'CPU DPC Rate',
    'Low-level CPU interrupt symptom retained mainly for diagnosis.',
    'numeric',
    'symptom',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'max',
    'p95',
    'max',
    'latest_value_numeric',
    '',
    'Diagnostic symptom without fixed thresholds yet.',
    1
),
(
    'node',
    'node.cpu_temperature_c',
    'CPU Temperature',
    'Thermal risk metric with strong current-state importance.',
    'numeric',
    'hardware_risk',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    85,
    '>=',
    95,
    [],
    [],
    'max',
    'max',
    'max',
    'latest',
    'latest_value_numeric',
    '',
    'Thermal critical condition should be able to override ranking.',
    1
),
(
    'node',
    'node.cpu_package_power_w',
    'CPU Package Power',
    'Hardware context metric for power and thermal diagnosis.',
    'numeric',
    'hardware_risk',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'avg',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Context metric without direct severity threshold yet.',
    1
),
(
    'node',
    'node.gpu_core_load_pct',
    'GPU Core Load',
    'GPU utilization metric mainly for workload detail and context.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'p95',
    'avg',
    'max',
    'latest_value_numeric',
    '',
    'Not part of MVP ranking but useful for GPU-aware environments.',
    1
),
(
    'node',
    'node.gpu_core_clock_mhz',
    'GPU Core Clock',
    'GPU hardware detail metric used for diagnosis.',
    'numeric',
    'hardware_risk',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'avg',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Diagnostic hardware detail without severity thresholds.',
    1
),
(
    'node',
    'node.gpu_memory_clock_mhz',
    'GPU Memory Clock',
    'GPU hardware detail metric used for diagnosis.',
    'numeric',
    'hardware_risk',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'avg',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Diagnostic hardware detail without severity thresholds.',
    1
),
(
    'node',
    'node.ssd_temperature_c',
    'SSD Temperature',
    'Storage thermal risk metric with ranking importance.',
    'numeric',
    'hardware_risk',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    70,
    '>=',
    80,
    [],
    [],
    'max',
    'max',
    'max',
    'max',
    'latest_value_numeric',
    '',
    'Drive-level metric where hottest drive matters.',
    1
),
(
    'node',
    'node.ssd_life_pct',
    'SSD Life Percent',
    'Storage wear indicator where lower remaining life is worse.',
    'numeric',
    'hardware_risk',
    'lower_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '<=',
    20,
    '<=',
    10,
    [],
    [],
    'min',
    'min',
    'min',
    'min',
    'latest_value_numeric',
    '',
    'Longer-term risk metric, not immediate override by default.',
    1
),
(
    'node',
    'node.ssd_available_spare_pct',
    'SSD Available Spare Percent',
    'Storage spare health indicator where lower is worse.',
    'numeric',
    'hardware_risk',
    'lower_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '<=',
    20,
    '<=',
    10,
    [],
    [],
    'min',
    'min',
    'min',
    'min',
    'latest_value_numeric',
    '',
    'Longer-term risk metric, not immediate override by default.',
    1
),
(
    'node',
    'node.ssd_percentage_used_pct',
    'SSD Percentage Used',
    'SSD wear usage indicator used mainly for health context.',
    'numeric',
    'hardware_risk',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'max',
    'avg',
    'max',
    'latest_value_numeric',
    '',
    'Contextual wear metric without explicit current thresholds yet.',
    1
),
(
    'node',
    'node.hostname',
    'Hostname',
    'Node identity label for detail and enrichment.',
    'text',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    '',
    '',
    '',
    '',
    '',
    'latest_value_text',
    'Inventory/detail metric excluded from operational ranking.',
    1
),
(
    'node',
    'node.os_product',
    'OS Product',
    'Operating system identity detail for enrichment.',
    'text',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    '',
    '',
    '',
    '',
    '',
    'latest_value_text',
    'Inventory/detail metric excluded from operational ranking.',
    1
),
(
    'node',
    'node.primary_ipv4',
    'Primary IPv4',
    'IP identity detail for enrichment and diagnostics.',
    'text',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    '',
    '',
    '',
    '',
    '',
    'latest_value_text',
    'Inventory/detail metric excluded from operational ranking.',
    1
),
(
    'node',
    'node.logical_cpu_count',
    'Logical CPU Count',
    'Static compute inventory context metric.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    '',
    '',
    'latest',
    'latest_value_numeric',
    '',
    'Inventory/detail metric excluded from operational ranking.',
    1
),
(
    'node',
    'node.process_count',
    'Process Count',
    'Runtime inventory/context metric for diagnosis.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'latest',
    'avg',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Useful context but not a primary severity signal.',
    1
),
(
    'node',
    'node.cpu_core_frequency_mhz',
    'CPU Core Frequency',
    'Hardware/runtime context metric for diagnosis.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'latest',
    'avg',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Useful context but not a primary severity signal.',
    1
),
(
    'node',
    'node.ssd_power_on_hours',
    'SSD Power On Hours',
    'Drive lifetime context metric.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    '',
    '',
    'max',
    'latest_value_numeric',
    '',
    'Inventory/detail metric excluded from operational ranking.',
    1
),
(
    'node',
    'node.ssd_power_on_count',
    'SSD Power On Count',
    'Drive lifecycle context metric.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    '',
    '',
    'max',
    'latest_value_numeric',
    '',
    'Inventory/detail metric excluded from operational ranking.',
    1
),
(
    'node',
    'node.ssd_data_read_gb',
    'SSD Data Read GB',
    'Drive lifecycle context metric.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    '',
    '',
    'sum',
    'latest_value_numeric',
    '',
    'Inventory/detail metric excluded from operational ranking.',
    1
),
(
    'node',
    'node.ssd_data_written_gb',
    'SSD Data Written GB',
    'Drive lifecycle context metric.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    '',
    '',
    'sum',
    'latest_value_numeric',
    '',
    'Inventory/detail metric excluded from operational ranking.',
    1
);

INSERT INTO metric_profile
(
    scope_type,
    metric_key,
    metric_label,
    description,
    value_kind,
    semantic_class,
    directionality,
    is_enabled,
    is_operational_metric,
    is_ranking_metric,
    override_on_critical,
    freshness_profile,
    fresh_after_sec,
    stale_after_sec,
    warning_operator,
    warning_threshold_numeric,
    critical_operator,
    critical_threshold_numeric,
    warning_text_values,
    critical_text_values,
    preferred_spatial_agg,
    preferred_temporal_agg_1m,
    preferred_temporal_agg_5m,
    preferred_summary_agg,
    preferred_numeric_field,
    preferred_text_field,
    notes,
    policy_version
)
VALUES
(
    'container',
    'container.name',
    'Container Name',
    'Container display name used for enrichment and operator-facing detail.',
    'text',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    '',
    '',
    '',
    '',
    '',
    'latest_value_text',
    'Inventory field for detail views.',
    1
),
(
    'container',
    'container.image',
    'Container Image',
    'Container image reference used for identity and diagnostic enrichment.',
    'text',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    '',
    '',
    '',
    '',
    '',
    'latest_value_text',
    'Inventory field for detail views.',
    1
),
(
    'container',
    'container.image_tag',
    'Container Image Tag',
    'Container image tag used for deployment/detail enrichment.',
    'text',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    '',
    '',
    '',
    '',
    '',
    'latest_value_text',
    'Inventory field for detail views.',
    1
),
(
    'container',
    'container.runtime_id',
    'Container Runtime ID',
    'Runtime identifier used for low-level troubleshooting.',
    'text',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    '',
    '',
    '',
    '',
    '',
    'latest_value_text',
    'Inventory field for detail views.',
    1
),
(
    'container',
    'container.status',
    'Container Status',
    'Human-readable container status retained for operator context.',
    'state',
    'state',
    'stateful',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'latest',
    'text_last',
    'text_last',
    'latest',
    '',
    'latest_value_text',
    'Context state metric; hard override is handled on container.state and container.health_status.',
    1
),
(
    'container',
    'container.state',
    'Container State',
    'Lifecycle state for run/stop semantics and operator ranking.',
    'state',
    'state',
    'stateful',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'worst_state',
    'text_last',
    'text_last',
    'latest',
    '',
    'latest_value_text',
    'Critical override is enforced in container_current_live when state is not running.',
    1
),
(
    'container',
    'container.health_status',
    'Container Health Status',
    'Container health probe result used for operator-first critical override.',
    'state',
    'state',
    'stateful',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'worst_state',
    'text_last',
    'text_last',
    'latest',
    '',
    'latest_value_text',
    'Critical override is enforced in container_current_live when health_status is unhealthy.',
    1
),
(
    'container',
    'container.restart_count',
    'Container Restart Count',
    'Restart symptom useful for repeated failure diagnosis.',
    'numeric',
    'symptom',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '>=',
    1,
    '>=',
    3,
    [],
    [],
    'max',
    'max',
    'max',
    'latest',
    'latest_value_numeric',
    '',
    'Soft restart-based degradation signal.',
    1
),
(
    'container',
    'container.service_name',
    'Container Service Name',
    'Logical service ownership reference for roll-up to service.',
    'text',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    '',
    '',
    '',
    '',
    '',
    'latest_value_text',
    'Join key for service roll-up and dashboard grouping.',
    1
),
(
    'container',
    'container.node_id',
    'Container Node ID',
    'Owning node identifier for topology and drill-down.',
    'text',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    '',
    '',
    '',
    '',
    '',
    'latest_value_text',
    'Join key for node drill-down and enrichment.',
    1
),
(
    'container',
    'container.port_binding_count',
    'Container Port Binding Count',
    'Inventory/context metric for exposed network bindings.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    '',
    '',
    'latest',
    'latest_value_numeric',
    '',
    'Inventory field excluded from operational severity.',
    1
),
(
    'container',
    'container.mount_count',
    'Container Mount Count',
    'Inventory/context metric for filesystem mounts.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    '',
    '',
    'latest',
    'latest_value_numeric',
    '',
    'Inventory field excluded from operational severity.',
    1
),
(
    'container',
    'container.network_count',
    'Container Network Count',
    'Inventory/context metric for attached networks.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'inventory',
    300,
    3600,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    '',
    '',
    'latest',
    'latest_value_numeric',
    '',
    'Inventory field excluded from operational severity.',
    1
),
(
    'container',
    'container.cpu_usage_pct',
    'Container CPU Usage',
    'Container CPU utilization used for current severity and ranking.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    85,
    '>=',
    95,
    [],
    [],
    'max',
    'p95',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Core operator-facing resource signal.',
    1
),
(
    'container',
    'container.memory_used_bytes',
    'Container Memory Used Bytes',
    'Raw memory usage used together with memory_limit_bytes to derive OOM-risk override.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'max',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Primary metric row used for derived memory ratio severity.',
    1
),
(
    'container',
    'container.memory_used_pct',
    'Container Memory Usage Percent',
    'Container memory utilization used for current severity and ranking.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '>=',
    85,
    '>=',
    95,
    [],
    [],
    'max',
    'p95',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Percent-based memory pressure signal alongside derived OOM risk.',
    1
),
(
    'container',
    'container.memory_limit_bytes',
    'Container Memory Limit Bytes',
    'Memory limit used as denominator for derived OOM-risk ratio.',
    'numeric',
    'inventory',
    'contextual',
    1,
    0,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'latest',
    'latest',
    'latest',
    'latest',
    'latest_value_numeric',
    '',
    'Supporting metric for derived ratio, not direct severity by itself.',
    1
),
(
    'container',
    'container.network_rx_bytes_sec',
    'Container Network RX',
    'Inbound network throughput used for activity context and trend analysis.',
    'numeric',
    'utilization',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    'avg',
    'avg',
    'sum',
    'latest_value_numeric',
    '',
    'Context metric without direct severity threshold.',
    1
),
(
    'container',
    'container.network_tx_bytes_sec',
    'Container Network TX',
    'Outbound network throughput used for activity context and trend analysis.',
    'numeric',
    'utilization',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    'avg',
    'avg',
    'sum',
    'latest_value_numeric',
    '',
    'Context metric without direct severity threshold.',
    1
),
(
    'container',
    'container.block_read_bytes_sec',
    'Container Block Read Throughput',
    'Storage throughput context metric used for trend and diagnosis.',
    'numeric',
    'symptom',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    'avg',
    'avg',
    'sum',
    'latest_value_numeric',
    '',
    'Diagnostic storage activity metric.',
    1
),
(
    'container',
    'container.block_write_bytes_sec',
    'Container Block Write Throughput',
    'Storage throughput context metric used for trend and diagnosis.',
    'numeric',
    'symptom',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    'avg',
    'avg',
    'sum',
    'latest_value_numeric',
    '',
    'Diagnostic storage activity metric.',
    1
),
(
    'container',
    'container.pid_count',
    'Container PID Count',
    'Runtime process count retained as contextual workload pressure signal.',
    'numeric',
    'symptom',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'max',
    'max',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Context signal without explicit threshold in MVP.',
    1
),
(
    'service',
    'service.container_count',
    'Service Container Count',
    'Declared total container count for the service cluster.',
    'numeric',
    'inventory',
    'contextual',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'latest',
    'latest',
    'latest',
    'latest',
    'latest_value_numeric',
    '',
    'Used together with running_container_count for business-state evaluation.',
    1
),
(
    'service',
    'service.running_container_count',
    'Service Running Container Count',
    'Current running child container count for service availability evaluation.',
    'numeric',
    'state',
    'lower_is_worse',
    1,
    1,
    1,
    1,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'latest',
    'latest',
    'latest',
    'latest',
    'latest_value_numeric',
    '',
    'Business-state severity is enforced in service_current_live from running vs total.',
    1
),
(
    'service',
    'service.cpu_usage_pct_sum',
    'Service CPU Usage Sum',
    'Aggregated service CPU workload used for trend and optional severity policy.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    'p95',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Thresholds can be enabled later through dictionary without SQL change.',
    1
),
(
    'service',
    'service.memory_used_bytes_sum',
    'Service Memory Used Bytes Sum',
    'Aggregated service memory workload used for trend and optional severity policy.',
    'numeric',
    'utilization',
    'higher_is_worse',
    1,
    1,
    0,
    0,
    'realtime',
    30,
    120,
    '',
    NULL,
    '',
    NULL,
    [],
    [],
    'sum',
    'max',
    'avg',
    'latest',
    'latest_value_numeric',
    '',
    'Thresholds can be enabled later through dictionary without SQL change.',
    1
);