export const GET_HEALTH_USE_CASE = Symbol('GET_HEALTH_USE_CASE');
export const SCAN_MARKER_USE_CASE = Symbol('SCAN_MARKER_USE_CASE');
export const GET_AR_ASSET_OVERVIEW_USE_CASE = Symbol(
  'GET_AR_ASSET_OVERVIEW_USE_CASE',
);
export const LIST_AR_WORK_ORDERS_USE_CASE = Symbol(
  'LIST_AR_WORK_ORDERS_USE_CASE',
);
export const CREATE_AR_WORK_ORDER_USE_CASE = Symbol(
  'CREATE_AR_WORK_ORDER_USE_CASE',
);
