
networks:
  redpanda-network:
    driver: bridge

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.15-fips
    command:
      - start
      - --mode=dev-container
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "8082:8082"
    networks:
      - redpanda-network

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v3.7.2
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
    ports:
      - "8080:8080"
    networks:
      - redpanda-network
    depends_on:
      - redpanda